Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
model_after = run_training(model, optimizer, epochs=10)
------------------


[31m---------------------------------------------------------------------------[39m
[31mImportError[39m                               Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[17][39m[32m, line 1[39m
[32m----> [39m[32m1[39m model_after = [43mrun_training[49m[43m([49m[43mmodel[49m[43m,[49m[43m [49m[43moptimizer[49m[43m,[49m[43m [49m[43mepochs[49m[43m=[49m[32;43m10[39;49m[43m)[49m

[36mCell[39m[36m [39m[32mIn[14][39m[32m, line 9[39m, in [36mrun_training[39m[34m(model, optimizer, epochs)[39m
[32m      5[39m accuracies = []
[32m      7[39m torch.autograd.set_detect_anomaly([38;5;28;01mTrue[39;00m)
[32m----> [39m[32m9[39m [38;5;28;01mfor[39;00m epoch [38;5;129;01min[39;00m [43mtrange[49m[43m([49m[43mepochs[49m[43m)[49m:
[32m     10[39m     training_loss, mean_loss = train(model, DEVICE, train_loader, optimizer, epoch, max_epochs=EPOCHS)
[32m     11[39m     test_loss, accuracy = test(model, DEVICE, test_loader, epoch)

[36mFile [39m[32m/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/tqdm/notebook.py:312[39m, in [36mtnrange[39m[34m(*args, **kwargs)[39m
[32m    310[39m [38;5;28;01mdef[39;00m[38;5;250m [39m[34mtnrange[39m(*args, **kwargs):
[32m    311[39m [38;5;250m    [39m[33;03m"""Shortcut for `tqdm.notebook.tqdm(range(*args), **kwargs)`."""[39;00m
[32m--> [39m[32m312[39m     [38;5;28;01mreturn[39;00m [43mtqdm_notebook[49m[43m([49m[38;5;28;43mrange[39;49m[43m([49m[43m*[49m[43margs[49m[43m)[49m[43m,[49m[43m [49m[43m*[49m[43m*[49m[43mkwargs[49m[43m)[49m

[36mFile [39m[32m/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/tqdm/notebook.py:234[39m, in [36mtqdm_notebook.__init__[39m[34m(self, *args, **kwargs)[39m
[32m    232[39m unit_scale = [32m1[39m [38;5;28;01mif[39;00m [38;5;28mself[39m.unit_scale [38;5;129;01mis[39;00m [38;5;28;01mTrue[39;00m [38;5;28;01melse[39;00m [38;5;28mself[39m.unit_scale [38;5;129;01mor[39;00m [32m1[39m
[32m    233[39m total = [38;5;28mself[39m.total * unit_scale [38;5;28;01mif[39;00m [38;5;28mself[39m.total [38;5;28;01melse[39;00m [38;5;28mself[39m.total
[32m--> [39m[32m234[39m [38;5;28mself[39m.container = [38;5;28;43mself[39;49m[43m.[49m[43mstatus_printer[49m[43m([49m[38;5;28;43mself[39;49m[43m.[49m[43mfp[49m[43m,[49m[43m [49m[43mtotal[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[43m.[49m[43mdesc[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[43m.[49m[43mncols[49m[43m)[49m
[32m    235[39m [38;5;28mself[39m.container.pbar = proxy([38;5;28mself[39m)
[32m    236[39m [38;5;28mself[39m.displayed = [38;5;28;01mFalse[39;00m

[36mFile [39m[32m/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/tqdm/notebook.py:108[39m, in [36mtqdm_notebook.status_printer[39m[34m(_, total, desc, ncols)[39m
[32m     99[39m [38;5;66;03m# Fallback to text bar if there's no total[39;00m
[32m    100[39m [38;5;66;03m# DEPRECATED: replaced with an 'info' style bar[39;00m
[32m    101[39m [38;5;66;03m# if not total:[39;00m
[32m   (...)[39m[32m    105[39m 
[32m    106[39m [38;5;66;03m# Prepare IPython progress bar[39;00m
[32m    107[39m [38;5;28;01mif[39;00m IProgress [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:  [38;5;66;03m# #187 #451 #558 #872[39;00m
[32m--> [39m[32m108[39m     [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m(WARN_NOIPYW)
[32m    109[39m [38;5;28;01mif[39;00m total:
[32m    110[39m     pbar = IProgress([38;5;28mmin[39m=[32m0[39m, [38;5;28mmax[39m=total)

[31mImportError[39m: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html

